before_script:
  # Github upload variables
  - export GH_OWNER=appditto
  - export GH_REPO_NAME=natrium_wallet_flutter
  - export GH_API=https://api.github.com
  - export GH_REPO=$GH_API/repos/$GH_OWNER/$GH_REPO_NAME

stages:
  - test
  - build
  - tag

run_tests:
  stage: test
  only:
    - tags
    - master
  tags:
    - appditto_mac
  script: 
    - flutter test

build_android:
  stage: build
  tags:
    - appditto_mac
  script:
    - cd android
    - fastlane build_android production:true

build_ios:
  stage: build
  tags:
    - appditto_mac
  script:
    - cd ios
    - fastlane build_ios


