before_script:
  # Github upload variables
  - export GH_OWNER=appditto
  - export GH_REPO_NAME=natrium_wallet_flutter
  - export GH_API=https://api.github.com
  - export GH_REPO=$GH_API/repos/$GH_OWNER/$GH_REPO_NAME

stages:
  - test
  - build
  - tag
  - deploy

run_tests:
  stage: test
  only:
    - tags
    - master
  tags:
    - appditto_mac
  script: 
    - flutter test

build_android:
  stage: build
  tags:
    - appditto_mac
  script:
    - cd android
    - fastlane build_android production:true

build_ios:
  stage: build
  tags:
    - appditto_mac
  script:
    - cd ios
    - fastlane build_ios

tag_version:
  stage: tag
  tags:
    - appditto_mac
  script:
    - ./ci/tag_version.sh
  when: manual

deploy_android_production:
  stage: deploy
  tags:
    - appditto_mac
  script:
    - cd android
    - fastlane deploy_android production:true
  when: manual

deploy_android_internal:
  stage: deploy
  tags:
    - appditto_mac
  script:
    - cd android
    - fastlane deploy_android internal:true
  when: manual

deploy_ios_production:
  stage: deploy
  tags:
    - appditto_mac
  script:
    - cd ios
    - fastlane deploy_ios
  when: manual


deploy_ios_testflight:
  stage: deploy
  tags:
    - appditto_mac
  script:
    - cd ios
    - fastlane deploy_ios testflight:true
  when: manual