before_script:
  # Github upload variables
  - export GH_OWNER=appditto
  - export GH_REPO_NAME=natrium_wallet_flutter
  - export GH_API=https://api.github.com
  - export GH_REPO=$GH_API/repos/$GH_OWNER/$GH_REPO_NAME
  # Flutter local configuration
  - echo flutter.sdk=$FLUTTER_PATH > android/local.properties
  - echo sdk.dir=$ANDROID_SDK_PATH >> android/local.properties
  - echo flutter.buildMode=release >> android/local.properties
  # Android signing
  - echo storePassword=$ANDROID_KEY_STORE_PASSWORD > android/key.properties
  - echo keyPassword=$ANDROID_KEY_PASSWORD >> android/key.properties
  - echo keyAlias=$ANDROID_KEY_ALIAS >> android/key.properties
  - echo storeFile=$ANDROID_KEYSTORE_PATH >> android/key.properties

stages:
  - test
  - update
  - build
  - tag
  - deploy
  - postdeploy

tests:
  stage: test
  only:
    - master
  tags:
    - appditto_mac
  script: 
    - flutter test

update:
  stage: update
  only:
    - master
  tags:
    - appditto_mac
  script:
    - flutter packages get
    - flutter packages upgrade

android:build:
  stage: build
  tags:
    - appditto_mac
  script:
    - cd android
    - fastlane build_android production:true

ios:build:
  stage: build
  tags:
    - appditto_mac
  script:
    - cd ios
    - fastlane build_ios

tag:create:
  stage: tag
  tags:
    - appditto_mac
  script:
    - ./ci/tag_version.sh
  when: manual

prod:android:deploy:
  stage: deploy
  tags:
    - appditto_mac
  script:
    - cd android
    - fastlane deploy_android production:true
  when: manual

prod:ios:deploy:
  stage: deploy
  tags:
    - appditto_mac
  script:
    - cd ios
    - fastlane deploy_ios
  when: manual

z:internal:android:deploy:
  stage: deploy
  tags:
    - appditto_mac
  script:
    - cd android
    - fastlane deploy_android internal:true
  when: manual

z:tflight:ios:deploy:
  stage: deploy
  tags:
    - appditto_mac
  script:
    - cd ios
    - fastlane deploy_ios testflight:true
  when: manual

upload:apk:github_release:
  stage: postdeploy
  tags:
    - appditto_mac
  script:
    ./ci/upload_android_github.sh
  needs: ["prod:android:deploy"]
  when: manual
