image: openjdk:8-jdk

variables:
  FLUTTER_VERSION: "https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.9.1+hotfix.6-stable.tar.xz"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  # flutter sdk setup
  - wget --output-document=flutter-sdk.tar.xz $FLUTTER_VERSION
  - tar -xf flutter-sdk.tar.xz
  - export PATH=$PATH:$PWD/flutter/bin
  - echo flutter.sdk=$PWD/flutter > android/local.properties
  # Github upload variables
  - export GH_OWNER=appditto
  - export GH_REPO_NAME=natrium_wallet_flutter
  - export GH_API=https://api.github.com
  - export GH_REPO=$GH_API/repos/$GH_OWNER/$GH_REPO
  - export AUTH="Authorization: token $GITHUB_API_TOKEN"

stages:
  - test
  - android_only_production_start
  - android_only_production_build
  - android_only_production_github_upload

run_tests:
  stage: test
  script: 
    - flutter test

# Pipeline for releasing android-only  into production
tag_release_android:
  stage: android_only_production_start
  script:
    - ./ci/tag_version.sh
  when: manual

build_release_android:
  stage: android_only_production_build
  script:
    - cd android
    - fastlane build_android upload:true production:true

upload_android_github:
  stage: android_only_production_github_upload
  script:
    - ./ci/upload_android_github.sh



