name: kalium_wallet_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  keyboard_actions: "^1.0.3"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Securley store data in a keystore
  flutter_secure_storage: ^3.1.2

  # Nano core functions
  flutter_nano_core: any

  # Shared prefs
  shared_preferences: ^0.4.3

  # Flare for animations
  flare_flutter: ^1.0.7

  # Websockets
  web_socket_channel: ^1.0.9

  # Platform-specific build info
  package_info: ^0.3.2

  # JSON Serialization
  json_annotation: ^2.0.0

  # Localization
  intl: ^0.15.7

  # BigDecimal alternative
  decimal: ^0.3.0

  # Logger
  logging: ^0.11.3+2

  # Native webview plugin
  flutter_webview_plugin: ^0.3.0+2

  # SQLite
  sqflite: ^0.13.0+1

  # Android/iOS path provider
  path_provider: ^0.4.1

  # TouchID/FaceID
  local_auth: ^0.3.1

  # RXDart
  rxdart : ^0.20.0

  # SVG
  flutter_svg: ^0.10.0

  # QR Codes
  qr_flutter: ^1.1.5 # Generator
  barcode_scan: ^0.0.8 # Scanner

  # Share images/text
  esys_flutter_share: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  json_serializable: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family:  KaliumIcons
      fonts:
        - asset: fonts/KaliumIcons.ttf
  assets:
    - assets/monkey.png
    - assets/monkeyQR.svg
    - assets/welcome_animation.flr
    - assets/send_animation.flr
    - assets/pulltorefresh_animation.flr
    - assets/loading_animation.flr
    - assets/sharecard_bananologo.svg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
