
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_ed25519:
    name: Build dependent library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: appditto/flutter_nano_ffi
          ref: refs/heads/master
      - name: Run cmake
        working-directory: android
        run: |
          cmake .
          make
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: libraries
          path: android/libed25519_blake2b.so

  run_tests:
    name: Run tests
    needs: build_ed25519
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master   
      - name: Download library
        uses: actions/download-artifact@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.x'
          channel: 'stable'

      - name: Set workspace in env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE

      - name: Run tests
        env:
          ED215519_SO_FILE: ${{ env.workspace }}/libraries/libed25519_blake2b.so
        run: |
          flutter pub get
          flutter test

  build_android:
    name: Build android
    needs: run_tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Build apk
        env:
          ED215519_SO_FILE: /Users/adapps/flutter_nano_ffi/android/libed25519_blake2b.dylib
        run: |
          echo ${{ secrets.ANDROID_KEYSTORE_PATH }} > android/key.properties
          echo ${{ secrets.ANDROID_KEY_ALIAS }} >> android/key.properties
          echo ${{ secrets.ANDROID_KEY_PASSWORD }} >> android/key.properties
          echo ${{ secrets.ANDROID_KEY_STORE_PASSWORD }} >> android/key.properties
          flutter pub get
          flutter build apk --release
